default:
  library: "librarypprd.library.nd.edu"
staging:
  assets: "asset.library.nd.edu"
  library: "librarypprd.library.nd.edu"
pre_production:
  assets: "asset.library.nd.edu"
  library: "librarypprd.library.nd.edu"
production:
  assets: "asset.library.nd.edu"
  library: "library.nd.edu"
